name: continuous integration

on:
  pull_request:
    paths:
      - '**/COMP1640/**'
      - '**/Domain/**'
      - '**/Infrastructure/**'
      - '**/Utilities/**'
      - '**/UnitTest/**'
      - '**/Dockerfile'
    branches:
      - develop
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 👌👌👌👌
        uses: actions/checkout@v3

      - name: Setup dotnet 🔧🔧🔧🔧
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencis 🔧🔧🔧🔧
        run: dotnet restore

      - name: Build app 🚀
        run: dotnet build -c Release --no-restore

      - name: Unit Test ✅✅✅✅
        run:  dotnet test -c Release --no-build

      - name: Publish app
        run: dotnet publish -c Release